version: "3.8"
services:
  db:
    image: postgres:14.5-alpine
    container_name: postgres
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=postgres

  server:
    build:
      context: ./server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SERVER_PORT=9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  gateway:
    build:
      context: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT-SERVER_URL=http://server:9090